server:
  port: 8082

erlogin:
  username: yanping
  userpass: 123321
  ip: localhost

spring:
  application:
    name: ribbon-consumer
  security:
    user:
      name: yanping
      password: 123321
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类
    driver-class-name: com.mysql.jdbc.Driver  #mysql去  com.mysql.jdbc.Driver  org.git.mm.mysql.Driver   新版本com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/txlcn-demo2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC  #数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5     #数据库连接池最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5    #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE  #加上这个就可以获取到HttpServletRequest
          thread:
            timeoutInMilliseconds: 10000
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
     defaultZone: http://${erlogin.username}:${erlogin.userpass}@${erlogin.ip}:1111/eureka/,http://${erlogin.username}:${erlogin.userpass}@${erlogin.ip}:1112/eureka/
  instance:
#      instance-id: ribbon-consumer
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 30
mybatis:
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: demo.serve.entity
